---
name: "HLSDownloader"
guid: "d0e54984-2989-45bc-b81e-c71838bdba50"
version: "1.1.0.5"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.HLSDownloader.dll"
changelog: >
  changelog
